name: project_bunny
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: mwho-mbp <monkey.onth3road@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  markdown: ^2.0.3

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.6.2
  build_web_compilers: ^2.1.4
  pedantic: ^1.7.0
